### ISSUE TITLE
Error on "Getting Data"

### ISSUE THREAD

**Issue by AdrianoCahete** [eshiota/save-my-fotolog#2]
When i try with default command:

```
Getting data from canalilha...
F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\cheerio\lib\parse.js:55
    var oldParent = node.parent || node.root,
                        ^

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\cheerio\lib\parse.js:55:25)
    at module.exports (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\cheerio\lib\parse.js:17:11)
    at Function.exports.load (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\cheerio\lib\static.js:19:14)
    at Request._callback (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\runner.js:116:25)
    at self.callback (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\request\request.js:199:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\request\request.js:821:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
```

With Skip Comments parameter:

```
Getting data from canalilha...
Getting all mosaic pagination links...
  - User has more than 6 pages of photos
F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\runner.js:49
    return parseInt(url.match(/\/(\d+)(?:\/|$)/)[1]);
                       ^

TypeError: Cannot read property 'match' of undefined
    at getUrlNumericPart (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\runner.js:49:24)
    at getMosaicPagesLinks (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\runner.js:153:21)
    at Request._callback (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\runner.js:118:21)
    at Request.self.callback (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\request\request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\request\request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\request\request.js:963:12)
```

Win10
Node 5.6.0

**Comment by AdrianoCahete** [comment]
Getting latest repo version, new install (just for make sure), and all commands (with and w/o parameters) give same results.
I thnk it's a OS problem, i can try to find any Win10 machine to test for you, if you want.

_Edit:_ You can use [MS Azure](http://tweaks.com/windows/67108/easily-evaluate-windows-10-on-microsoft-azure/) as trial to install a WIn10 VM.

```
Getting data from canalilha...
Getting all mosaic pagination links...
  - User has only one page of photos, no pagination
  - Built links for 1 pages
Getting all posts links...
F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\cheerio\lib\parse.js:55
    var oldParent = node.parent || node.root,
                        ^

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\cheerio\lib\parse.js:55:25)
    at module.exports (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\cheerio\lib\parse.js:17:11)
    at Function.exports.load (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\cheerio\lib\static.js:19:14)
    at Request._callback (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\runner.js:209:29)
    at self.callback (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\request\request.js:199:22)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at Request.onRequestError (F:\Projetos\00.Github\save-my-fotolog\save-my-fotolog-master\node_modules\request\request.js:821:8)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
``
```
